### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by ArmsTina** [Game351-Group/Final-Project#2]
Terrain / Charis, Sage
Prefabs (Obstacles And Collectibles) / Young, Sage
Environment (Waters, weather?) / Charis

**Comment by ArmsTina** [comment]
Play Map + Cutscene Map are added by Charis

**Comment by CharisPC** [comment]
Sounds + Particle systems are added by Charis

**Comment by CharisPC** [comment]
Hidden level map + tutorial island add on by Sage
