### ISSUE TITLE
Others

### ISSUE THREAD

**Issue by ArmsTina** [Game351-Group/Final-Project#3]
UI (Include Menu etc) / Quinn, Young
Cut Scenes (Cinemachine) / Sage
VFX (Particles) / Charis
Sounds / Charis
Physics / Young
Systems (HP, Goal Point etc) / Young

Last Edited May 1st:
Cut Scenes (Cinemachine) / Sage
UI (Include Menu etc) / Quinn, Young

**Comment by ArmsTina** [comment]
edited : UI (Include Menu etc) / Quinn, Young

**Comment by ArmsTina** [comment]
Added:
Colliders are added (except saws).
A basic script for savepoints (on GameManager).
Basic script for what happens when a player falls, fish scores, and make savepoints when player hits (on PlayerSystem).
Added basic Ingame-UI images, texts, and scripts

**Comment by ArmsTina** [comment]
edited: Cut Scenes (Cinemachine) / Sage

**Comment by ArmsTina** [comment]
Added:
Saws and spikes now have colliders
Script for what happens when a player touches obstacles (lose 1 life and respawn)
Script for moving saws

Adjusted terrain collider

**Comment by CharisPC** [comment]
Sounds + Particle systems added by Charis
